const scholarshipSeeds = [
  {
    id: 'national-scholarship',
    name: '国家奖学金',
    category: 'national',
    type: '奖学金',
    sponsor: '国家资助',
    amountMode: 'fixed',
    amountText: '10000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '10000元/人/学年', note: '同一学年不能同时获得国家励志奖学金' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向学习成绩和综合表现特别突出的二年级及以上学生。',
    collegeKey: '',
    collegeName: '',
    quota: '约80人',
    deadline: '按学校年度评审通知执行',
    intro: '奖励在校期间学习成绩优异、社会实践、创新能力和综合素质等方面特别突出的学生。',
    conditions: [
      '具有中华人民共和国国籍',
      '热爱祖国，拥护中国共产党的领导',
      '遵守宪法法律和学校规章制度',
      '诚实守信，道德品质优良',
      '评审学年度学业成绩排名与综合考评成绩排名均位于前10%（含）',
      '二年级（含）以上学生',
    ],
    guide: '按学校通知提交成绩排名、综合表现和相关证明材料。',
    openForApply: true,
  },
  {
    id: 'national-encourage-scholarship',
    name: '国家励志奖学金',
    category: 'national',
    type: '奖学金',
    sponsor: '国家资助',
    amountMode: 'fixed',
    amountText: '6000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '6000元/人/学年', note: '同一学年不能同时获得国家奖学金' }],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向品学兼优且家庭经济困难的二年级及以上学生。',
    collegeKey: '',
    collegeName: '',
    quota: '约1000人',
    deadline: '按学校年度评审通知执行',
    intro: '奖励品学兼优、家庭经济困难的学生。',
    conditions: [
      '具有中华人民共和国国籍',
      '热爱祖国，拥护中国共产党的领导',
      '遵守宪法法律和学校规章制度',
      '诚实守信，道德品质优良',
      '评审学年度学业成绩排名与综合考评成绩排名不低于前50%',
      '评审学年度无不及格科目',
      '家庭经济困难，生活简朴',
      '二年级（含）以上学生',
    ],
    guide: '完成家庭经济困难认定后，按学校通知提交申请材料。',
    openForApply: true,
  },
  {
    id: 'national-grant',
    name: '国家助学金',
    category: 'national',
    type: '助学金',
    sponsor: '国家资助',
    amountMode: 'tiered',
    amountText: '2500-5000元/人/学年（一般分三个等级）',
    amountTiers: [
      { label: '一类贫困生', amount: '5000元/人/学年', note: '对应特别困难' },
      { label: '二类贫困生', amount: '3700元/人/学年', note: '对应困难' },
      { label: '三类贫困生', amount: '2500元/人/学年', note: '对应一般困难' },
    ],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '按家庭经济困难认定结果分档资助。',
    collegeKey: '',
    collegeName: '',
    quota: '根据家庭经济困难认定情况确定',
    deadline: '按学校年度资助评审安排执行',
    intro: '用于资助家庭经济困难学生完成学业。',
    conditions: [
      '具有中华人民共和国国籍',
      '热爱祖国，拥护中国共产党的领导',
      '遵守宪法法律和学校规章制度',
      '诚实守信，道德品质优良',
      '家庭经济困难，生活简朴',
      '勤奋学习，积极上进',
      '可同时申请并获得国家奖学金或国家励志奖学金',
    ],
    guide: '结合家庭经济困难认定结果和学校名额安排分档评审。',
    openForApply: true,
  },
  {
    id: 'national-grant-veteran',
    name: '国家助学金（退役士兵学生）',
    category: 'national',
    type: '助学金',
    sponsor: '国家资助',
    amountMode: 'fixed',
    amountText: '3700元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '3700元/人/学年', note: '与普通国家助学金不重复' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向全部全日制在校退役士兵学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际退役士兵学生人数确定',
    deadline: '按学校年度资助评审安排执行',
    intro: '面向全日制在校退役士兵学生的专项助学金。',
    conditions: ['全部全日制在校退役士兵学生'],
    guide: '按学校通知和退役士兵身份材料办理。',
    openForApply: true,
  },
  {
    id: 'student-loan',
    name: '国家助学贷款（生源地）',
    category: 'national',
    type: '资助项目',
    sponsor: '国家资助',
    amountMode: 'range',
    amountText: '本专科最高不超过20000元/人/年；全日制研究生最高不超过25000元/人/年',
    amountTiers: [
      { label: '本专科', amount: '最高不超过20000元/人/年', note: '按生源地政策办理' },
      { label: '全日制研究生', amount: '最高不超过25000元/人/年', note: '按生源地政策办理' },
    ],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '家庭经济困难学生可按规定申请。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际',
    deadline: '按生源地学生资助管理部门受理时间办理',
    intro: '家庭经济困难学生可在户籍所在地申请生源地信用助学贷款。',
    conditions: ['家庭经济困难学生', '按户籍所在县学生资助管理部门要求办理'],
    guide: '准备身份证明、录取或在读证明等材料，按生源地流程办理。',
    openForApply: true,
  },
  {
    id: 'military-education-aid',
    name: '服兵役国家教育资助',
    category: 'national',
    type: '资助项目',
    sponsor: '国家资助',
    amountMode: 'range',
    amountText: '学费补偿、国家助学贷款代偿及学费减免，本科生最高不超过20000元/人/年',
    amountTiers: [{ label: '本科生', amount: '最高不超过20000元/人/年', note: '2024年秋季学期起执行' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '适用于应征入伍、招收为士官、退役复学或入学的高校学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际',
    deadline: '按学校和兵役资助政策安排办理',
    intro: '面向应征入伍服义务兵役、招收为士官、退役后复学或入学的高等学校学生。',
    conditions: ['应征入伍服义务兵役', '招收为士官', '退役后复学或入学的高等学校学生'],
    guide: '按学校通知提交入伍、退役或复学相关证明材料。',
    openForApply: true,
  },
  {
    id: 'green-channel',
    name: '绿色通道',
    category: 'national',
    type: '资助项目',
    sponsor: '国家资助',
    amountMode: 'fixed',
    amountText: '先办理入学手续，入学后再开展认定和资助',
    amountTiers: [{ label: '入学支持', amount: '先办理入学手续', note: '入学后由学校资助部门根据具体情况给予资助' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '适用于家庭经济确实困难、无法缴纳学费的新生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际',
    deadline: '新生报到阶段办理',
    intro: '被录取入学且家庭经济确实困难的新生，可先办理入学手续。',
    conditions: ['被录取入学', '家庭经济确实困难', '无法缴纳学费的新生'],
    guide: '报到时向学校说明情况，经登记后先办理入学。',
    openForApply: true,
  },
  {
    id: 'nanyue-disability-aid',
    name: '南粤扶残助学工程',
    category: 'local',
    type: '助学金',
    sponsor: '地方政府资助',
    amountMode: 'fixed',
    amountText: '15000元/人（一次性）',
    amountTiers: [{ label: '一次性资助', amount: '15000元/人', note: '本科生' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向广东省户籍新入学残疾人本专科大学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际申请和审核通过确定名额',
    deadline: '按当地残联和学校通知申报',
    intro: '面向符合条件的广东省户籍新入学残疾人本专科大学生。',
    conditions: ['具有广东省户籍', '新入学残疾人本专科大学生'],
    guide: '向入学前户籍所在地县（市、区）级残联提出申请。',
    openForApply: true,
  },
  {
    id: 'three-support-loan-compensation',
    name: '“三支一扶”国家助学贷款代偿',
    category: 'local',
    type: '资助项目',
    sponsor: '地方政府资助',
    amountMode: 'fixed',
    amountText: '代偿在校学习期间获得的国家助学贷款本息',
    amountTiers: [{ label: '贷款代偿', amount: '代偿国家助学贷款本息', note: '服务期满考核合格后按政策执行' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向毕业后到农村基层从事“三支一扶”并符合条件的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际申请和审核通过确定名额',
    deadline: '按相关专项通知办理',
    intro: '面向毕业后到农村基层从事支农、支教、支医和帮扶乡村振兴工作的学生。',
    conditions: ['服务期满考核合格', '继续在经济欠发达地区基层工作满1年以上'],
    guide: '按专项政策提交服务期和贷款材料。',
    openForApply: true,
  },
  {
    id: 'guangdong-freshman-aid',
    name: '广东省家庭经济困难大学新生资助',
    category: 'local',
    type: '助学金',
    sponsor: '地方政府资助',
    amountMode: 'fixed',
    amountText: '不超过6000元/人',
    amountTiers: [{ label: '最高标准', amount: '不超过6000元/人', note: '按实际申请和审核通过确定' }],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向当年考入学校的广东省户籍家庭经济困难一年级新生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际申请和审核通过确定名额',
    deadline: '新生入学当年按通知申报',
    intro: '面向广东省户籍、家庭经济困难、无力支付当年学费的一年级新生。',
    conditions: ['广东省户籍', '当年考入学校的一年级新生', '家庭经济困难，无力支付当年学费'],
    guide: '按学校通知提交户籍、录取和困难情况相关材料。',
    openForApply: true,
  },
  {
    id: 'temporary-hardship-subsidy',
    name: '临时困难补贴',
    category: 'school',
    type: '助学金',
    sponsor: '学校资助',
    amountMode: 'range',
    amountText: '金额不等，根据实际突发情况而定',
    amountTiers: [{ label: '按实际核定', amount: '金额不等', note: '根据实际突发困难情况确定' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: ['R04', 'R15', 'R16', 'R17', 'R18', 'R19'],
    restrictionNote: '面向遭遇重大疾病、严重意外、灾害等突发困难的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际',
    deadline: '困难发生后及时申报',
    intro: '用于帮扶因重大疾病、严重意外、自然灾害等导致家庭经济困难的学生。',
    conditions: [
      '学生本人罹患重大疾病或遭受严重意外伤害',
      '学生家庭因父母（抚养人）罹患重大疾病或遭受严重意外伤害',
      '学生家庭遭遇严重自然灾害或安全事故造成严重经济损失',
      '其他特殊情况导致家庭经济困难并严重影响正常学习和生活',
    ],
    guide: '联系辅导员并按学校通知提交相关困难证明材料。',
    openForApply: true,
  },
  {
    id: 'work-study',
    name: '勤工助学',
    category: 'school',
    type: '资助项目',
    sponsor: '学校资助',
    amountMode: 'fixed',
    amountText: '19.8元/人/小时',
    amountTiers: [{ label: '岗位报酬', amount: '19.8元/人/小时', note: '原则上每周不超过8小时，每月不超过40小时' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '优先考虑家庭经济困难学生，同等条件下学习成绩优秀者优先。',
    collegeKey: '',
    collegeName: '',
    quota: '约600个校内固定岗位',
    deadline: '按岗位开放时间报名申请',
    intro: '学校安排校内勤工助学岗位，帮助学生改善学习生活条件。',
    conditions: [
      '遵守国家法律法规和学校规章制度，道德品行良好',
      '学有余力，生活简朴，身体健康，能利用课余时间上岗',
      '优先考虑家庭经济困难学生',
    ],
    guide: '按学校岗位需求和通知报名申请。',
    openForApply: true,
  },
  {
    id: 'comprehensive-scholarship',
    name: '综合奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'tiered',
    amountText: '800-2000元/人/学年（分三档）',
    amountTiers: [
      { label: '一等奖', amount: '2000元/人/学年', note: '控制在本年级本专业学生总人数的3%以内' },
      { label: '二等奖', amount: '1000元/人/学年', note: '控制在本年级本专业学生总人数的5%以内' },
      { label: '三等奖', amount: '800元/人/学年', note: '控制在本年级本专业学生总人数的7%以内' },
    ],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向上一学年全面发展、品学兼优的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '一等奖3%以内，二等奖5%以内，三等奖7%以内',
    deadline: '按学校学年评优通知为准',
    intro: '用于奖励在上一学年中全面发展、品学兼优的学生，设一、二、三等奖。',
    conditions: ['上一学年全面发展、品学兼优'],
    guide: '按学校综合测评和评优通知申报评审。',
    openForApply: true,
  },
  {
    id: 'single-item-scholarship',
    name: '单项奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'fixed',
    amountText: '600元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '600元/人/学年', note: '控制在本年级本专业学生总人数的12%以内' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向在思想品德、学业表现、体育、美育和劳动素养方面表现突出的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '控制在本年级本专业学生总人数的12%以内',
    deadline: '按学校学年评优通知为准',
    intro: '分为思想品德方向、学业表现方向、体育素养方向、美育素养方向和劳动素养方向。',
    conditions: ['上一学年在单项素养方面表现突出'],
    guide: '按学校评优通知和方向要求申请。',
    openForApply: true,
  },
  {
    id: 'graduate-scholarship',
    name: '毕业生奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'fixed',
    amountText: '1500元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '1500元/人/学年', note: '获奖名额控制在当年应届毕业年级学生人数的5%以内' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向综合表现突出且兼具专长和业绩的毕业生。',
    collegeKey: '',
    collegeName: '',
    quota: '控制在当年应届毕业年级学生人数的5%以内',
    deadline: '按学校毕业年级评优通知为准',
    intro: '以学生在校期间综合表现为主要依据，兼顾某一方面专长和业绩。',
    conditions: ['以在校期间综合表现为主要依据', '兼顾某一方面专长和业绩'],
    guide: '按学校毕业生奖学金通知提交申请材料。',
    openForApply: true,
  },
  {
    id: 'president-scholarship',
    name: '校长奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'fixed',
    amountText: '8000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '8000元/人/学年', note: '获奖名额控制在参评学生人数的1%以内' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '学校最高层次奖学金，面向全面发展或单项能力特别突出的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '控制在参评学生人数的1%以内',
    deadline: '按学校年度评优通知为准',
    intro: '校长奖学金是学校最高层次的奖学金。',
    conditions: ['德智体美劳全面发展', '综合素质高或单项能力特别突出'],
    guide: '按学校校长奖学金评审通知申报。',
    openForApply: true,
  },
  {
    id: 'intl-freshman-scholarship',
    name: '来华留学新生奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'fixed',
    amountText: '10000元/人',
    amountTiers: [{ label: '新生奖学金', amount: '10000元/人', note: '符合申请条件新生总人数的100%' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向符合条件的来华留学本科新生。',
    collegeKey: '',
    collegeName: '',
    quota: '符合申请条件新生总人数的100%',
    deadline: '按学校国际学生奖学金通知为准',
    intro: '面向来华留学本科新生的入学奖学金。',
    conditions: ['本科生申请者', '高中学业GPA成绩≥2.5或学业平均成绩≥70分'],
    guide: '按学校来华留学生奖学金通知提交申请。',
    openForApply: true,
  },
  {
    id: 'intl-undergraduate-cn-scholarship',
    name: '来华留学本科（中文授课）奖学金',
    category: 'school',
    type: '奖学金',
    sponsor: '学校资助',
    amountMode: 'tiered',
    amountText: '7000-20000元/人/学年（分三档）',
    amountTiers: [
      { label: '一等奖学金', amount: '20000元/人', note: '在校留学生总人数的10%（不含新生）' },
      { label: '二等奖学金', amount: '10000元/人', note: '在校留学生总人数的30%（不含新生）' },
      { label: '三等奖学金', amount: '7000元/人', note: '在校留学生总人数的50%（不含新生）' },
    ],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向在读满一学年的全日制来华留学本科生（中文授课）。',
    collegeKey: '',
    collegeName: '',
    quota: '按在校留学生比例分档设置',
    deadline: '按学校国际学生奖学金通知为准',
    intro: '面向在读满一学年的全日制来华留学本科生（中文授课）设立。',
    conditions: ['在读满一学年的全日制来华留学本科生（中文授课）', '上一学年课程考试平均成绩≥70分', '单科成绩≥60分'],
    guide: '按学校通知提交成绩和在读情况材料。',
    openForApply: true,
  },
  {
    id: 'military-excellent-student-award',
    name: '应征入伍优秀学生奖励',
    category: 'school',
    type: '奖励',
    sponsor: '学校资助',
    amountMode: 'tiered',
    amountText: '1000-50000元/人（按荣誉等级）',
    amountTiers: [
      { label: '一等功', amount: '一次性奖励50000元/人', note: '以最高级别奖励为准，不重复奖励' },
      { label: '二等功', amount: '一次性奖励20000元/人', note: '以最高级别奖励为准，不重复奖励' },
      { label: '三等功', amount: '一次性奖励10000元/人', note: '以最高级别奖励为准，不重复奖励' },
      { label: '优秀士兵/优秀义务兵', amount: '一次性奖励1000元/人', note: '以最高级别奖励为准，不重复奖励' },
    ],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向服役期间荣立功勋或获评优秀士兵的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际申请和审核通过名额确定',
    deadline: '按学校相关专项通知申报',
    intro: '对服役期间荣立功勋或获评优秀士兵（优秀义务兵）的学生给予奖励。',
    conditions: ['服役期间荣立一等功、二等功、三等功，或评为优秀士兵、优秀义务兵'],
    guide: '按学校通知提交立功或获奖证明材料。',
    openForApply: true,
  },
  {
    id: 'military-enlistment-student-award',
    name: '应征入伍学生奖励',
    category: 'school',
    type: '奖励',
    sponsor: '学校资助',
    amountMode: 'tiered',
    amountText: '1000-10000元/人或参照综合奖学金标准奖励',
    amountTiers: [
      { label: '高原边远艰苦地区服役', amount: '一次性奖励10000元/人', note: '到新疆、西藏等军队确定的高原、边远、艰苦地区服役的义务兵' },
      { label: '在校生和新生入伍', amount: '参照综合奖学金二等奖标准奖励', note: '按学校政策执行' },
      { label: '毕业生入伍', amount: '参照综合奖学金一等奖标准奖励', note: '按学校政策执行' },
    ],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向符合学校入伍奖励政策的学生。',
    collegeKey: '',
    collegeName: '',
    quota: '根据实际申请和审核通过名额确定',
    deadline: '按学校相关专项通知申报',
    intro: '对应征入伍学生按服役去向和身份类别给予奖励。',
    conditions: ['在校生、新生或毕业生应征入伍', '或到新疆、西藏等高原、边远、艰苦地区服役的义务兵'],
    guide: '按学校通知提交入伍证明和相关材料。',
    openForApply: true,
  },
  {
    id: 'lihanhun-aid',
    name: '李汉魂助学金',
    category: 'social',
    type: '助学金',
    sponsor: '社会奖助学金',
    amountMode: 'fixed',
    amountText: '2000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '2000元/人/学年', note: '新生重点倾向家庭经济特别困难学生' }],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向湛江校区在籍在校本科家庭经济困难学生。',
    collegeKey: '',
    collegeName: '',
    quota: '40名',
    deadline: '按年度通知为准',
    intro: '面向湛江校区在籍在校本科学生中的家庭经济困难学生。',
    conditions: ['湛江校区在籍在校本科学生', '评选年度被认定为家庭经济困难学生', '学习努力、成绩良好'],
    guide: '按学校通知提交申请材料。',
    openForApply: true,
  },
  {
    id: 'ph-red-coral-aid',
    name: '红珊瑚助学金',
    category: 'social',
    type: '助学金',
    sponsor: '红珊瑚奖助学金（药学院）',
    amountMode: 'fixed',
    amountText: '2500元/人/年',
    amountTiers: [{ label: '助学金部分', amount: '2500元/人/年', note: '奖励20名' }],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向药学院二至四年级本科贫困生。',
    collegeKey: 'pharmacy',
    collegeName: '药学院',
    quota: '20名',
    deadline: '按药学院通知为准',
    intro: '发放对象为药学院正式注册的全日制二至四年级本科贫困生。',
    conditions: ['药学院正式注册的全日制二至四年级本科生', '家庭经济困难'],
    guide: '按学院通知和综合素质评价结果评选。',
    openForApply: true,
  },
  {
    id: 'ph-red-coral-scholarship',
    name: '红珊瑚奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '红珊瑚奖助学金（药学院）',
    amountMode: 'fixed',
    amountText: '2000元/人/年',
    amountTiers: [{ label: '奖学金部分', amount: '2000元/人/年', note: '奖励25名' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向药学院优秀考研录取学生。',
    collegeKey: 'pharmacy',
    collegeName: '药学院',
    quota: '25名',
    deadline: '按药学院通知为准',
    intro: '发放对象为药学院应届本科生中被本院第一志愿录取为全日制硕士研究生的学生。',
    conditions: ['药学院应届本科生', '被广东医科大学药学院第一志愿录取为全日制硕士研究生', '综合成绩排名位列本学院考研录取考生前25名'],
    guide: '按学院通知提交录取证明和成绩材料。',
    openForApply: true,
  },
  {
    id: 'ph-innovation-fund',
    name: '应用实践创新基金',
    category: 'social',
    type: '奖学金',
    sponsor: '应用实践创新基金（药学院）',
    amountMode: 'fixed',
    amountText: '2000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '2000元/人/学年', note: '10名' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向“药学+应用化学联合学位”二至四年级学生。',
    collegeKey: 'pharmacy',
    collegeName: '药学院',
    quota: '10名',
    deadline: '按药学院通知为准',
    intro: '面向“药学+应用化学联合学位”二至四年级学生设立。',
    conditions: ['“药学+应用化学联合学位”二至四年级学生', '学业加权成绩班级排名前列且无不及格记录，或考上本校研究生并取得优秀成绩'],
    guide: '按学院通知提交成绩和相关证明材料。',
    openForApply: true,
  },
  {
    id: 'ph-alumni-aid',
    name: '药苑校友基金助学金',
    category: 'social',
    type: '助学金',
    sponsor: '药苑校友基金（药学院）',
    amountMode: 'fixed',
    amountText: '2500元/人/年',
    amountTiers: [{ label: '助学金部分', amount: '2500元/人/年', note: '奖励18名' }],
    requiresPovertyRecognition: true,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向药学院二至四年级本科贫困生。',
    collegeKey: 'pharmacy',
    collegeName: '药学院',
    quota: '18名',
    deadline: '按药学院通知为准',
    intro: '发放对象为药学院正式注册的全日制二至四年级本科贫困生。',
    conditions: ['药学院正式注册的全日制二至四年级本科生', '家庭经济困难'],
    guide: '按学院通知和综合素质评价结果评选。',
    openForApply: true,
  },
  {
    id: 'ph-alumni-scholarship',
    name: '药苑校友基金奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '药苑校友基金（药学院）',
    amountMode: 'fixed',
    amountText: '2000元/人/年',
    amountTiers: [{ label: '奖学金部分', amount: '2000元/人/年', note: '奖励10名' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向药学院优秀考研录取学生。',
    collegeKey: 'pharmacy',
    collegeName: '药学院',
    quota: '10名',
    deadline: '按药学院通知为准',
    intro: '发放对象为药学院应届本科生中被本院第一志愿录取为全日制硕士研究生的学生。',
    conditions: ['药学院应届本科生', '被广东医科大学药学院第一志愿录取为全日制硕士研究生', '综合成绩排名位列本学院考研录取考生前10名'],
    guide: '按学院通知提交录取证明和成绩材料。',
    openForApply: true,
  },
  {
    id: 'public-wten-survey',
    name: '万人调查奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '万人调查奖学金（公共卫生学院）',
    amountMode: 'fixed',
    amountText: '1000元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '1000元/人/学年', note: '5名' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向公共卫生学院统计学非毕业年级全日制本科生。',
    collegeKey: 'public-health',
    collegeName: '公共卫生学院',
    quota: '5名',
    deadline: '按学院通知为准',
    intro: '面向广东医科大学统计学非毕业年级的全日制在校本科生。',
    conditions: ['统计学非毕业年级全日制在校本科生'],
    guide: '具体按照《万人调查奖学金管理办法》执行。',
    openForApply: true,
  },
  {
    id: 'medtech-lanwei',
    name: '兰卫教育基金',
    category: 'social',
    type: '奖学金',
    sponsor: '兰卫教育基金（医学技术学院）',
    amountMode: 'range',
    amountText: '1000-5000元不等，年设奖金30000元',
    amountTiers: [{ label: '年度奖金', amount: '1000-5000元不等', note: '年设奖金30000元' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向医学技术学院非毕业年级全日制在校本科生。',
    collegeKey: 'medical-technology',
    collegeName: '医学技术学院',
    quota: '根据实际申请和审核通过名额确定',
    deadline: '按学院通知为准',
    intro: '面向广东医科大学医学技术学院非毕业年级的全日制在校本科生。',
    conditions: ['医学技术学院非毕业年级全日制在校本科生'],
    guide: '具体按照《兰卫教育基金管理办法》执行。',
    openForApply: true,
  },
  {
    id: 'medtech-kefang',
    name: '科方奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '科方奖学金（医学技术学院）',
    amountMode: 'range',
    amountText: '2500-10000元/人/学年',
    amountTiers: [{ label: '分档标准', amount: '2500-10000元/人/学年', note: '按管理办法执行' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向医学技术学院非毕业年级全日制在校本科生。',
    collegeKey: 'medical-technology',
    collegeName: '医学技术学院',
    quota: '根据实际申请和审核通过名额确定',
    deadline: '按学院通知为准',
    intro: '面向广东医科大学医学技术学院非毕业年级的全日制在校本科生。',
    conditions: ['医学技术学院非毕业年级全日制在校本科生'],
    guide: '具体按照《科方奖学金管理办法》执行。',
    openForApply: true,
  },
  {
    id: 'sc-guohua-academic',
    name: '国华学业奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '国华学业奖学金（第二临床医学院）',
    amountMode: 'fixed',
    amountText: '1500元/人/学年',
    amountTiers: [{ label: '固定标准', amount: '1500元/人/学年', note: '12名' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '奖励对象仅限于第二临床医学院康复治疗学和康复物理治疗专业本科学生。',
    collegeKey: 'second-clinical',
    collegeName: '第二临床医学院',
    quota: '12名',
    deadline: '按学院通知为准',
    intro: '奖励对象仅限于第二临床医学院康复治疗学专业和康复物理治疗专业本科学生。',
    conditions: [
      '热爱祖国，自觉遵守宪法和法律，遵守学校规章制度，无违纪记录',
      '诚实守信，品行端正，举止文明',
      '综合测评成绩排名、学业成绩排名均在年级专业前30%以内，无不及格科目',
      '本年度志愿服务时数达到20小时',
    ],
    guide: '按学院通知提交成绩、志愿服务和专业发展材料。',
    openForApply: true,
  },
  {
    id: 'sc-guohua-sports',
    name: '国华体育奖学金',
    category: 'social',
    type: '奖学金',
    sponsor: '国华体育奖学金（第二临床医学院）',
    amountMode: 'range',
    amountText: '无固定金额，实行奖金金额总量控制，每年发放奖金不超过5750元',
    amountTiers: [{ label: '年度总额', amount: '每年不超过5750元', note: '视上一年度参赛结果而定' }],
    requiresPovertyRecognition: false,
    allowedRecognitionRuleIds: [],
    restrictionNote: '面向在校级及以上正规综合性官方体育赛事中取得优异成绩的学生。',
    collegeKey: 'second-clinical',
    collegeName: '第二临床医学院',
    quota: '具体奖励名额视上一年度学生参赛结果而定',
    deadline: '按学院通知为准',
    intro: '奖励在校级及以上正规综合性官方体育运动赛事中取得优异成绩的学生。',
    conditions: [
      '热爱祖国，拥护党的领导，自觉遵守宪法和法律，遵守学校规章制度，无违规违纪情况',
      '在校运会或校级及以上正规综合性官方体育赛事中取得优异成绩',
      '遵守比赛规则，无违反体育精神的言行举止',
    ],
    guide: '按学院通知提交赛事成绩和申请材料。',
    openForApply: true,
  },
]

const homeBanners = [
  { id: 'banner-national', title: '国家奖学金', subtitle: '特别优秀学生重点支持', themeStart: '#4A90E2', themeEnd: '#7FB3F4' },
  { id: 'banner-grant', title: '国家助学金', subtitle: '按家庭经济困难认定分档资助', themeStart: '#FFD166', themeEnd: '#F8E08B' },
  { id: 'banner-comprehensive', title: '综合奖学金', subtitle: '上一学年全面发展学生可申报', themeStart: '#6BCB77', themeEnd: '#99E2A2' },
]

const announcements = [
  {
    id: 'announcement-001',
    coverImage: '/teacher/logo.png',
    title: '2026年春季学期国家助学金分档公示说明',
    content:
      '国家助学金将根据困难认定审核结果自动匹配一二三类资助档次，请同学们及时在“我的-认定申请”中查看状态。对认定结果有异议的同学请在公示期内提交补充材料。',
    attachments: [
      {
        id: 'announcement-001-attachment-1',
        name: '国家助学金分档说明.txt',
        type: 'text/plain',
        size: 28,
        sizeLabel: '28B',
        contentBase64: 'QW5ub3VuY2VtZW50IGF0dGFjaG1lbnQgZGVtby4K',
      },
    ],
    publishedAt: '2026-04-07T09:00:00.000Z',
    updatedAt: '2026-04-07T09:00:00.000Z',
    publisher: '学生资助管理中心',
  },
  {
    id: 'announcement-002',
    coverImage: '/teacher/logo.png',
    title: '社会奖助学金申报通道已开放',
    content:
      '社会奖助学金与学院专项项目已开放线上申请。请在首页进入“奖助学金列表”查看项目详情、资格条件和申报截止时间，按要求上传完整材料。',
    attachments: [],
    publishedAt: '2026-04-06T10:30:00.000Z',
    updatedAt: '2026-04-06T10:30:00.000Z',
    publisher: '学生资助管理中心',
  },
  {
    id: 'announcement-003',
    coverImage: '/teacher/logo.png',
    title: '困难认定补充材料提交提醒',
    content:
      '认定状态为“退回补充”的同学，请在截止日前补充佐证材料并重新提交。逾期未提交将影响本学年助学金评审。',
    attachments: [],
    publishedAt: '2026-04-05T15:20:00.000Z',
    updatedAt: '2026-04-05T15:20:00.000Z',
    publisher: '学生资助管理中心',
  },
]

const categoryTabs = [
  { key: 'national', label: '国家资助' },
  { key: 'local', label: '地方政府资助' },
  { key: 'school', label: '学校资助' },
  { key: 'social', label: '社会奖助学金' },
]

module.exports = {
  scholarshipSeeds,
  homeBanners,
  announcements,
  categoryTabs,
}
