const studentSeeds = [
  {
    id: 'student-001',
    studentNo: '20250001',
    name: '张晓雨',
    gender: '女',
    college: '药学院',
    collegeKey: 'pharmacy',
    major: '药学',
    className: '药学1班',
    grade: '大二',
    phone: '13800000000',
    currentRecognitionStatus: '审核通过',
    currentRecognitionLevel: '特别困难',
    currentPovertyTag: '一类贫困生',
    confirmedRecognitionRuleIds: ['R01', 'R36'],
    confirmedRecognitionLabels: ['脱贫家庭学生', '2人（含本人）及以上在上学'],
    currentRecognitionScore: 93,
  },
  {
    id: 'student-002',
    studentNo: '20250002',
    name: '李文婷',
    gender: '女',
    college: '公共卫生学院',
    collegeKey: 'public-health',
    major: '预防医学',
    className: '预防医学2班',
    grade: '大三',
    phone: '13800000002',
    currentRecognitionStatus: '待审核',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
  {
    id: 'student-003',
    studentNo: '20250003',
    name: '陈宇航',
    gender: '男',
    college: '医学技术学院',
    collegeKey: 'medical-technology',
    major: '医学检验技术',
    className: '医检2班',
    grade: '大四',
    phone: '13800000003',
    currentRecognitionStatus: '审核通过',
    currentRecognitionLevel: '困难',
    currentPovertyTag: '二类贫困生',
    confirmedRecognitionRuleIds: ['R17', 'R24', 'R36'],
    confirmedRecognitionLabels: ['家庭遭受重大自然灾害，受灾严重（一年以上两年以内）', '父母均没有工作（不含农村种植户或养殖户）', '2人（含本人）及以上在上学'],
    currentRecognitionScore: 56,
  },
  {
    id: 'student-004',
    studentNo: '20250004',
    name: '王嘉怡',
    gender: '女',
    college: '第二临床医学院',
    collegeKey: 'second-clinical',
    major: '临床医学',
    className: '临床3班',
    grade: '大二',
    phone: '13800000004',
    currentRecognitionStatus: '驳回',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
  {
    id: 'student-005',
    studentNo: '20250005',
    name: '何思远',
    gender: '男',
    college: '公共卫生学院',
    collegeKey: 'public-health',
    major: '卫生检验与检疫',
    className: '卫检1班',
    grade: '大一',
    phone: '13800000005',
    currentRecognitionStatus: '审核通过',
    currentRecognitionLevel: '一般困难',
    currentPovertyTag: '三类贫困生',
    confirmedRecognitionRuleIds: ['R20'],
    confirmedRecognitionLabels: ['父母一方抚养'],
    currentRecognitionScore: 35,
  },
  {
    id: 'student-006',
    studentNo: '20250006',
    name: '刘嘉宁',
    gender: '女',
    college: '药学院',
    collegeKey: 'pharmacy',
    major: '临床药学',
    className: '临药2班',
    grade: '大一',
    phone: '13800000006',
    currentRecognitionStatus: '未申请',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
  {
    id: 'student-007',
    studentNo: '20250007',
    name: '周雨彤',
    gender: '女',
    college: '公共卫生学院',
    collegeKey: 'public-health',
    major: '预防医学',
    className: '预防医学1班',
    grade: '大二',
    phone: '13800000007',
    currentRecognitionStatus: '未申请',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
  {
    id: 'student-008',
    studentNo: '20250008',
    name: '黄子轩',
    gender: '男',
    college: '医学技术学院',
    collegeKey: 'medical-technology',
    major: '医学检验技术',
    className: '医检1班',
    grade: '大二',
    phone: '13800000008',
    currentRecognitionStatus: '未申请',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
  {
    id: 'student-009',
    studentNo: '20250009',
    name: '林思涵',
    gender: '女',
    college: '第二临床医学院',
    collegeKey: 'second-clinical',
    major: '康复治疗学',
    className: '康复1班',
    grade: '大三',
    phone: '13800000009',
    currentRecognitionStatus: '未申请',
    currentRecognitionLevel: '未认定',
    currentPovertyTag: '未认定',
    confirmedRecognitionRuleIds: [],
    confirmedRecognitionLabels: [],
    currentRecognitionScore: 0,
  },
]

module.exports = {
  studentSeeds,
}
